version: '3.9'

services:

  azure-sql-db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: azure-sql-edge
    restart: unless-stopped
    user: root
    environment:
          SA_PASSWORD: "UPjhg?eLKhAs9?:*jR%Ta?-zz"
          ACCEPT_EULA: "Y"
          MSSQL_PID: Developer
    ports:
        - "1433:1433"
    volumes:
        - nexuscore-storage:/var/opt/mssql
    networks:
        - bridge-network

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    volumes:
        - nexuscore-storage:/data
    ports:
        - "6379:6379"
    networks:
        - bridge-network
  
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
        MONGO_INITDB_ROOT_USERNAME: nexuscore
        MONGO_INITDB_ROOT_PASSWORD: UPjhg?eLKhAs9?:*jR%Ta?-zz
    volumes:
        - nexuscore-storage:/data/db
        - ./src/Solution.Utilities/docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
        - "27017:27017"
    networks:
        - bridge-network

networks:
  bridge-network:
    driver: bridge

volumes:
  nexuscore-storage:
    external: true
    
# docker volume create nexuscore-storage