version: '3.9'

services:

  azure-sql-db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: azure-sql-edge
    restart: unless-stopped
    user: root
    environment:
          SA_PASSWORD: "UPjhg?eLKhAs9?:*jR%Ta?-zz"
          ACCEPT_EULA: "Y"
          MSSQL_PID: Developer
    ports:
        - "1433:1433"
    volumes:
        - nexuscore-storage:/var/opt/mssql
    networks:
        - bridge-network

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    volumes:
        - nexuscore-storage:/data
    ports:
        - "6379:6379"
    networks:
        - bridge-network

networks:
  bridge-network:
    driver: bridge

volumes:
  nexuscore-storage:
    external: true
    
# docker volume create nexuscore-storage